Console.WriteLine("╔════════════════════════════════════════════════════════════╗");
Console.WriteLine("║   ONE HEALTH - Sistema de Monitorização Urbana (TP2)       ║");
Console.WriteLine("║   Sistemas Distribuídos 2025/2026                          ║");
Console.WriteLine("╚════════════════════════════════════════════════════════════╝");
Console.WriteLine();
Console.WriteLine("Componentes (TP2):");
Console.WriteLine("  1. RabbitMQ    → docker run -d -p 5672:5672 -p 15672:15672 rabbitmq:3-management");
Console.WriteLine("  2. PreProcessor→ dotnet run --project src/PreProcessor  (gRPC :50051)");
Console.WriteLine("  3. AnalysisService → cd src/AnalysisService && python service.py (:50052)");
Console.WriteLine("  4. Server      → dotnet run --project src/Server  (TCP :8000, HTTP :8080)");
Console.WriteLine("  5. Gateway     → dotnet run --project src/Gateway -- config/sensors.csv");
Console.WriteLine("  6. Sensor      → dotnet run --project src/Sensor -- S101");
Console.WriteLine();
Console.WriteLine("Dashboard: http://localhost:8080");
Console.WriteLine();
