# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"-\n\tDataPoint\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"\xac\x01\n\x0f\x41nalysisRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\t\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x15\n\ranalysis_type\x18\x06 \x01(\t\x12(\n\x0b\x64\x61ta_points\x18\x07 \x03(\x0b\x32\x13.analysis.DataPoint\"\xb6\x01\n\x0e\x41nalysisResult\x12\x15\n\ranalysis_type\x18\x01 \x01(\t\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\x0f\n\x07std_dev\x18\x03 \x01(\x01\x12\x11\n\tmin_value\x18\x04 \x01(\x01\x12\x11\n\tmax_value\x18\x05 \x01(\x01\x12\x12\n\nrisk_level\x18\x06 \x01(\t\x12\x0f\n\x07summary\x18\x07 \x01(\t\x12\x10\n\x08patterns\x18\x08 \x03(\t\x12\x11\n\ttimestamp\x18\t \x01(\t2Q\n\x0f\x41nalysisService\x12>\n\x07\x41nalyze\x12\x19.analysis.AnalysisRequest\x1a\x18.analysis.AnalysisResultB\x0b\xaa\x02\x08\x41nalysisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Analysis'
  _globals['_DATAPOINT']._serialized_start=28
  _globals['_DATAPOINT']._serialized_end=73
  _globals['_ANALYSISREQUEST']._serialized_start=76
  _globals['_ANALYSISREQUEST']._serialized_end=248
  _globals['_ANALYSISRESULT']._serialized_start=251
  _globals['_ANALYSISRESULT']._serialized_end=433
  _globals['_ANALYSISSERVICE']._serialized_start=435
  _globals['_ANALYSISSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
